Turn on:
  description: Turn on the light.
Turn off:
  description: Turn off the light.
set brightness:
  description: Set the brightness of the light.
  fields:
    brightness:
      description: The brightness value to set.
      example: 255
